# Generated by Django 4.1.7 on 2023-03-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='anon',
            field=models.CharField(default=6, max_length=250),
            preserve_default=False,
        ),
    ]
