# Generated by Django 4.1.7 on 2023-03-28 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='anon',
        ),
    ]
